---
- name: remove older versions
  package:
    name: "{{item}}"
    state: absent
  with_items:
    - docker
    - docker-client
    - docker-client-latest
    - docker-common
    - docker-latest
    - docker-latest-logrotate
    - docker-logrotate
    - docker-selinux
    - docker-engine-selinux
    - docker-engine

- name: Add a docker repo
  get_url:
    url: "http://download.docker.com/linux/centos/docker-ce.repo"
    dest: /etc/yum.repos.d/docer-ce.repo
    mode: 0444

- name: Enable Docker Edge repo and Docker Test repo
  ini_file: 
    path: /etc/yum.repos.d/docer-ce.repo  
    section: "{{item}}"
    option: enabled 
    value: 0
  with_items: 
     - docker-ce-edge
     - docker-ce-test

- name: Install Docker and their dependecies
  package: 
    name: "{{item}}" 
    state: latest
  with_items:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - docker-ce

- name: Start Docker service
  service: 
    name: docker
    state: started
    enabled: yes
